# Generated by Django 5.1.6 on 2025-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_hairstylist_requires_password_reset_hairstylist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstylist',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
    ]
