# Generated by Django 5.1.6 on 2025-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_hairstylist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstylist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
