# Generated by Django 5.1.6 on 2025-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_hairstylist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstylist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
